### ISSUE TITLE
Fix that some input-elements are not reachable when a virtual keyboard is displayed

### ISSUE THREAD

**Issue by YeGaSoft** [YeGaSoft/DnDCharCtor#15]
When a virtual keyboard is displayed (especially relevant to mobile platforms) all elements should be still reachable.

**Comment by YeGaSoft** [comment]
Also on Android, when trying to enter numbers in the numbers field (or when focusing the number field) it always removes all characters.

**Comment by mnmnk43434** [comment]
Hello, we tried to solve the issue.

This is what we did:

Modified the scrollToInput.js file to include a more robust solution for handling virtual keyboard display. Updated the EditCharacter.razor file to use the new JavaScript function and adjust the layout when inputs are focused.

You can review changes in this commit: https://github.com/mnmnk43434/YeGaSoft-DnDCharCtor-15/commit/843db0ecb3157ab63b859a9a62101fcef7df43bd.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by YeGaSoft** [comment]
The problem is only in the MAUI-App-Version but not in the PWA.
So we could use the Workaround for Blazor Hybrid.
See: https://github.com/dotnet/maui/issues/14197
